# Generated by Django 4.2.3 on 2023-08-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': ('Клиент',),
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(verbose_name='Время рассылки')),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='Периодичность')),
                ('status', models.CharField(default='Создана', verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsender.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': ('Рассылка',),
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Тело письма')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mailsender.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': ('Сообщение',),
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('status', models.CharField(blank=True, null=True, verbose_name='Статус')),
                ('server_ans', models.CharField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsender.message', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': ('Лог',),
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
